?start: iff

?iff: implication
    | implication "<->" iff -> iff

?implication: or
    | or "->" implication -> implication

?or: and
    | and "|" or -> or

?and: negation
    | negation "&" and -> and

?negation: "~" expression -> neg
    | expression

?expression: "(" iff ")"
    | atom

?atom: "T" -> true
    | "F" -> false
    | variable -> var

?variable: ("a".."z")+

%import common.WS_INLINE
%ignore WS_INLINE